spring:
  application:
    name: societe-task
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/societe_task}
    username: ${DB_USERNAME:societe}
    password: ${DB_PASSWORD:societe}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    problemdetails:
      enabled: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.societe.task.application: ${APPLICATION_LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health,info
